apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  JWT_SECRET: "2a357ddfddc231752e315a25cecd64be27474664db6ec2b3aaa113f2b795c94b"
  DB_PASSWORD: "eventhub_password"
  DATABASE_URL: "postgresql://user:eventhub_password@postgres:5432/eventhub?schema=public"