apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "development"
  PORT: "3000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "eventhub"
  DB_USER: "user"
  MONGO_URI: "mongodb://eventhub-mongo:27017/analytics"