services:
  postgres:
    image: postgres:15
    container_name: eventhub_postgres
    restart: always
    env_file:
      - ./eventhub-backend/.env.docker
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d eventhub" ]
      interval: 10s
      timeout: 10s
      retries: 10

  mongo:
    image: mongo:latest
    container_name: eventhub_mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  # redis:
  #   image: redis:latest
  #   container_name: eventhub_redis
  #   restart: always
  #   ports:
  #     - '6379:6379'

  backend:
    build: ./eventhub-backend
    container_name: eventhub_backend
    restart: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./eventhub-backend/.env
    volumes:
      - ./eventhub-backend:/app
      - /app/node_modules

  frontend:
    build: ./eventhub-frontend
    container_name: eventhub_frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./eventhub-frontend/.env
    volumes:
      - ./eventhub-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
  mongo_data: