apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 5173;

        # Tout ce qui commence par /api est redirigé vers le backend K8s
        location /api {
            proxy_pass http://eventhub-backend:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Tout le reste va vers le frontend React K8s
        location / {
            proxy_pass http://eventhub-frontend:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }