FROM node:latest

WORKDIR /app

COPY ./package.json ./package-lock.json ./

RUN npm install

# Install dev dependencies
RUN npm install --save-dev ts-node-dev


COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
