@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyM2VkZWQ5LWVhNDQtNDlhNi1iYTZmLWYwMDgyOWIzMjJhZSIsImZpc3J0TmFtZSI6IkRhbWllbiIsImxhc3ROYW1lIjoiSiIsImVtYWlsIjoiZGFtaWVuQGdtYWlsLmNvbSIsInBob25lIjoiMDEyMzQ1Njc4OSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2ODU1NTk4MSwiZXhwIjoxNzY4NjQyMzgxfQ.dXBZAMAtxQEWjctBsT4PUfmWQyeO9fK2AkQ-bYIzj_M
@Eventid=38804403-5581-43ba-b4e8-bedc993a6003

### Login
POST http://localhost:8000/api/events/login
Content-Type: application/json

{
    "email": "damien@gmail.com",
    "password": "azerty"
}

### POST Event
POST http://localhost:8000/api/events/create
Content-Type: application/json
Authorization: Bearer {{token}}

{           
    "title": "JAVAFEST",
    "description": "Event",
    "date": "2026-01-16T19:25:28.984Z",
    "venue": "10 Rue de Jeanne",
    "capacity": 100,
    "organizer": "Damien J",
    "category": "Api",
    "price": 55
}


### GET Events
GET http://localhost:8000/api/events/
Authorization: Bearer {{token}}

### GET Event By ID 
GET http://localhost:8000/api/events/{{Eventid}}
Authorization: Bearer {{token}}

### PUT Event with JWT
PUT http://localhost:8000/api/events/{{Eventid}}
Authorization: Bearer {{token}}
Content-Type: application/json

{           
    "title": "JAVAFEST 2026",
    "description": "Event",
    "capacity": 3000,
    "price": 75
}

### DELETE Event with JWT
DELETE http://localhost:8000/api/events/{{Eventid}}
Authorization: Bearer {{token}}
