FROM node:20-alpine

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le code source
COPY . .

# Compiler TypeScript
RUN npx tsc

# Exposer le port
EXPOSE 5000

# Lancer le serveur compilé
CMD ["node", "dist/server.js"]

