@startuml EventHub

start
:Visiteur accède à EventHub;

partition Visiteur {
    if (A un compte ?) then (oui)
        :Se connecter;
        :Compte validé;
    else
        :Créer un compte;
        :Se connecter;
    endif
}

partition VisiteurConnecte {
    fork
        :Consulter événements;
        :Consulter détails événement;
        if (Souhaite commenter ?) then (oui)
        :Saisir contenu;
        :Envoyer commentaire;
        endif
    fork again
        if (Souhaite se déconnecter ?) then (oui)
            :Déconnexion;
            stop
        endif
    end fork

    if (Est-il Organisateur ?) then (oui)
        partition Organisateur {
            :L'utilisateur hérite les droits précédents;
            fork
                if (Créer événement ?) then (oui)
                    :Créer via EvenementController;
                endif
            fork again
                if (Modifier événement ?) then (oui)
                    :Modifier événement;
                endif
            fork again
                if (Supprimer événement ?) then (oui)
                    :Supprimer événement;
                endif
            end fork
        }
    endif

    if (Est-il Modérateur ?) then (oui)
        partition Moderateur {
            :L'utilisateur hérite les droits précédents;
            fork
                if (Signaler commentaire ?) then (oui)
                    :Signaler via CommentaireController;
                endif
            fork again
                if (Supprimer commentaire ?) then (oui)
                    :Supprimer via ModerationController;
                endif
            fork again
                if (Bannir utilisateur ?) then (oui)
                    :Bannir via ModerationController;
                endif
            fork again
                if (Débannir utilisateur ?) then (oui)
                    :Débannir via ModerationController;
                endif
            end fork
        }
    endif

    if (Est-il Administrateur ?) then (oui)
        partition Administrateur {
            :L'utilisateur hérite les droits précédents;
            fork
                if (Supprimer compte ?) then (oui)
                    :Supprimer via AdministrateurController;
                endif
            fork again
                :Consulter statistiques;
            end fork
        }
    endif
}
stop

@enduml
