name: CI Quality Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./eventhub-backend 

    steps:
      - [cite_start]name: Checkout du code [cite: 5]
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installation des dépendances
        run: npm install

      - [cite_start]name: Exécution des tests unitaires [cite: 5]
        run: npm test